=== HwaipyLab/Crystics/Crystics/src/main/resources/com/hwaipy/crystics/Sellmeier.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//Hwaipy//DTD Sellmeier 1.0//EN
    SYSTEM ID  : http://www.hwaipy.com/crystics/Sellmeier.dtd
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->

<!ELEMENT sellmeier (medium+)>
<!ELEMENT medium (symbol,name,alias*,refractive+)>
<!ELEMENT symbol (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT alias (#PCDATA)>
<!ELEMENT refractive (range,((nx,ny,nz)|(ne,no)),reference)>
<!ELEMENT range (from,to)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT nx (formula)>
<!ELEMENT ny (formula)>
<!ELEMENT nz (formula)>
<!ELEMENT ne (formula)>
<!ELEMENT no (formula)>
<!ELEMENT formula ((system|external),coefficients)>
<!ELEMENT system (#PCDATA)>
<!ELEMENT external (#PCDATA)>
<!ELEMENT coefficients (#PCDATA)>
<!ELEMENT reference ((doi|reference-id),description?)>
<!ELEMENT doi (#PCDATA)>
<!ELEMENT reference-id (#PCDATA)>
<!ELEMENT description (#PCDATA)>

=== HwaipyLab/Crystics/Crystics/src/main/resources/com/hwaipy/crystics/Sellmeiers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE sellmeier PUBLIC "-//Hwaipy//DTD Sellmeier 1.0//EN" "http://www.hwaipy.com/crystics/Sellmeier.dtd">

<sellmeier>
  <medium>
    <symbol>KTiOPO4</symbol>
    <name>potassium titanyl phosphate</name>
    <alias>KTP</alias>
    <refractive>
      <range>
        <from>0.43</from>
        <to>3.54</to>
      </range>
      <nx>
        <formula>
          <system>4</system>
          <coefficients>3.29100,0.04140,0,0.03978,1,9.35522,0,31.45571,1</coefficients>
        </formula>
      </nx>
      <ny>
        <formula>          
          <system>4</system>
          <coefficients>3.45018,0.04341,0,0.04597,1,16.98825,0,39.43799,1</coefficients>
        </formula>
      </ny>
      <nz>
        <formula>          
          <system>4</system>
          <coefficients>4.59423,0.06206,0,0.04763,1,110.80672,0,86.12171,1</coefficients>
        </formula>
      </nz>
      <reference>
        <doi>10.1364/AO.41.005040</doi>
        <description>K. Kato and E. Takaoka. Sellmeier and thermo-optic dispersion formulas for KTP, Appl. Opt. 41, 5040-5044 (2002).</description>
      </reference>
    </refractive>
  </medium>
</sellmeier>
